[pytest]
pythonpath = .
testpaths = tests
addopts = -p no:cacheprovider
filterwarnings =
    ignore:.*InsecureKeyLengthWarning.*:UserWarning
    ignore:.*StarletteDeprecationWarning.*:DeprecationWarning