"""add_user_id_to_order_items

Revision ID: 1eb2a6d1b0dc
Revises: c2f3a8b94d1e
Create Date: 2026-08-20 20:10:41.406034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb2a6d1b0dc'
down_revision: Union[str, Sequence[str], None] = 'c2f3a8b94d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_order_items_user_id'), 'order_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_user_id'), table_name='order_items')
    op.drop_column('order_items', 'user_id')
    # ### end Alembic commands ###
